---

version: '3'

vars:
  TARGET: microbit

tasks:
  hello-tinygo-fmt:
    cmds:
      - go build -o 01-hello-tinygo-fmt/main-go 01-hello-tinygo-fmt/main.go
      - strip -o 01-hello-tinygo-fmt/main-go-strip 01-hello-tinygo-fmt/main-go
      - tinygo build -o 01-hello-tinygo-fmt/main-tinygo 01-hello-tinygo-fmt/main.go
      - strip -o 01-hello-tinygo-fmt/main-tinygo-strip 01-hello-tinygo-fmt/main-tinygo
      - ls -lhS 01-hello-tinygo-fmt/main-*
    silent: true

  hello-tinygo-os:
    cmds:
      - go build -o 01-hello-tinygo-os/main-go 01-hello-tinygo-os/main.go
      - strip -o 01-hello-tinygo-os/main-go-strip 01-hello-tinygo-os/main-go
      - tinygo build -o 01-hello-tinygo-os/main-tinygo 01-hello-tinygo-os/main.go
      - strip -o 01-hello-tinygo-os/main-tinygo-strip 01-hello-tinygo-os/main-tinygo
      - ls -lhS 01-hello-tinygo-os/main-*
    silent: true

  hello-tinygo-println:
    cmds:
      - go build -o 01-hello-tinygo-println/main-go 01-hello-tinygo-println/main.go
      - strip -o 01-hello-tinygo-println/main-go-strip 01-hello-tinygo-println/main-go
      - tinygo build -o 01-hello-tinygo-println/main-tinygo 01-hello-tinygo-println/main.go
      - strip -o 01-hello-tinygo-println/main-tinygo-strip 01-hello-tinygo-println/main-tinygo
      - tinygo build -gc=leaking -o 01-hello-tinygo-println/main-tinygo-gc-leaking 01-hello-tinygo-println/main.go
      - strip -o 01-hello-tinygo-println/main-tinygo-gc-leaking-strip 01-hello-tinygo-println/main-tinygo-gc-leaking
      - ls -lhS 01-hello-tinygo-println/main-*
    silent: true

  hello-microbit:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} 02-hello-microbit/main.go
    silent: true

  interrupt:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} 03-interrupt/main.go
    silent: true

  goroutine:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} 04-goroutine/main.go
    silent: true

  goroutine-external-led:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} 04-goroutine-2/main.go
    silent: true

  memory-baseline:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} 05-memory-1-baseline/main.go
    silent: true

  memory-bbs-data:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} 05-memory-2-bbs-data/main.go
    silent: true

  memory-stack:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} 05-memory-3-stack/main.go
    silent: true

  cpu-fibonacci:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} 06-cpu-fibonacci/main.go
    silent: true
