---

version: '3'

vars:
  TARGET: microbit

tasks:
  hello-tinygo-fmt:
    cmds:
      - go build -o 01-hello-tinygo-fmt/main-go 01-hello-tinygo-fmt/main.go
      - strip -o 01-hello-tinygo-fmt/main-go-strip 01-hello-tinygo-fmt/main-go
      - tinygo build -o 01-hello-tinygo-fmt/main-tinygo 01-hello-tinygo-fmt/main.go
      - strip -o 01-hello-tinygo-fmt/main-tinygo-strip 01-hello-tinygo-fmt/main-tinygo
      - tinygo build -no-debug -scheduler=none -panic=trap -gc=leaking -o 01-hello-tinygo-fmt/main-tinygo-optimized 01-hello-tinygo-fmt/main.go
      - strip -o 01-hello-tinygo-fmt/main-tinygo-optimized-strip 01-hello-tinygo-fmt/main-tinygo-optimized
      - ls -lS 01-hello-tinygo-fmt/main-*
    silent: true
    aliases: [01]

  hello-tinygo-os:
    cmds:
      - go build -o 02-hello-tinygo-os/main-go 02-hello-tinygo-os/main.go
      - strip -o 02-hello-tinygo-os/main-go-strip 02-hello-tinygo-os/main-go
      - tinygo build -o 02-hello-tinygo-os/main-tinygo 02-hello-tinygo-os/main.go
      - strip -o 02-hello-tinygo-os/main-tinygo-strip 02-hello-tinygo-os/main-tinygo
      - tinygo build -no-debug -scheduler=none -panic=trap -gc=leaking -o 02-hello-tinygo-os/main-tinygo-optimized 02-hello-tinygo-os/main.go
      - strip -o 02-hello-tinygo-os/main-tinygo-optimized-strip 02-hello-tinygo-os/main-tinygo-optimized
      - ls -lS 02-hello-tinygo-os/main-*
    silent: true
    aliases: [02]

  hello-tinygo-println:
    cmds:
      - go build -o 03-hello-tinygo-println/main-go 03-hello-tinygo-println/main.go
      - strip -o 03-hello-tinygo-println/main-go-strip 03-hello-tinygo-println/main-go
      - tinygo build -o 03-hello-tinygo-println/main-tinygo 03-hello-tinygo-println/main.go
      - strip -o 03-hello-tinygo-println/main-tinygo-strip 03-hello-tinygo-println/main-tinygo
      - tinygo build -no-debug -scheduler=none -panic=trap -gc=leaking -o 03-hello-tinygo-println/main-tinygo-optimized 03-hello-tinygo-println/main.go
      - strip -o 03-hello-tinygo-println/main-tinygo-optimized-strip 03-hello-tinygo-println/main-tinygo-optimized
      - ls -lS 03-hello-tinygo-println/main-*
    silent: true
    aliases: [03]

  hello-microbit:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./04-hello-microbit
    silent: true
    aliases: [04]

  hello-microbit-heart:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./05-hello-microbit-heart
    silent: true
    aliases: [05]

  cpu-fibonacci:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./06-cpu-fibonacci
    silent: true
    aliases: [06]

  cpu-fibonacci-linux:
    cmds:
      - tinygo run ./06-cpu-fibonacci
    silent: true
    aliases: [06-linux]

  memory-baseline:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./07-memory-1-baseline
    silent: true
    aliases: [07]

  memory-bbs-data:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./08-memory-bbs-data
    silent: true
    aliases: [08]

  memory-heap:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./09-memory-heap-allocation
    silent: true
    aliases: [09]

  gc-conservative:
    cmds:
      - tinygo flash -gc=conservative -size=short -target={{.TARGET}} ./10-gc
    silent: true
    aliases: [10]

  gc-leaking:
    cmds:
      - tinygo flash -gc=leaking -size=short -target={{.TARGET}} ./10-gc
    silent: true
    aliases: [10-leaking]

  memory-stack:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./11-memory-stack
    silent: true
    aliases: [11]

  goroutine:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./12-goroutine
    silent: true
    aliases: [12]

  goroutine-external-led:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./13-goroutine-external-led
    silent: true
    aliases: [13]

  goroutines-memory:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./14-goroutines-memory
    silent: true
    aliases: [14]

  interrupt:
    cmds:
      - tinygo flash -size=short -target={{.TARGET}} ./15-interrupt
    silent: true
    aliases: [15]

  clean:
    cmds:
      - git clean -fx
    slient: true

  cam:
    cmds:
      - capwindow 0
    silent: true
